name: Coding Standards

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs_check:
    name: PHPCS check
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Configure Composer cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-versions }}-${{ matrix.dependency-versions }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-versions }}-${{ matrix.dependency-versions }}-composer-${{ hashFiles('**/composer.lock') }}
            ${{ runner.os }}-${{ matrix.php-versions }}-${{ matrix.dependency-versions }}-composer-

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install

      - name: Run Coding Standards tests
        run: composer phpcs
